[2024-07-18 05:58:56,938] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v3.third_task 2024-07-18T05:58:54.630913+00:00 [queued]>
[2024-07-18 05:58:56,952] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v3.third_task 2024-07-18T05:58:54.630913+00:00 [queued]>
[2024-07-18 05:58:56,953] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-07-18 05:58:56,953] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-07-18 05:58:56,954] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-07-18 05:58:56,973] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): third_task> on 2024-07-18T05:58:54.630913+00:00
[2024-07-18 05:58:56,977] {standard_task_runner.py:52} INFO - Started process 837 to run task
[2024-07-18 05:58:56,982] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_first_dag_v3', 'third_task', '2024-07-18T05:58:54.630913+00:00', '--job-id', '16', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp1vh8o3xu', '--error-file', '/tmp/tmp33jxhfkh']
[2024-07-18 05:58:56,986] {standard_task_runner.py:77} INFO - Job 16: Subtask third_task
[2024-07-18 05:58:57,051] {logging_mixin.py:104} INFO - Running <TaskInstance: our_first_dag_v3.third_task 2024-07-18T05:58:54.630913+00:00 [running]> on host a868c7bacc12
[2024-07-18 05:58:57,124] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v3
AIRFLOW_CTX_TASK_ID=third_task
AIRFLOW_CTX_EXECUTION_DATE=2024-07-18T05:58:54.630913+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-18T05:58:54.630913+00:00
[2024-07-18 05:58:57,126] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2024-07-18 05:58:57,133] {bash.py:158} INFO - Running command: echo hello world, this is the third task, it will run after first task and at the same time task 2
[2024-07-18 05:58:57,144] {bash.py:169} INFO - Output:
[2024-07-18 05:58:57,147] {bash.py:173} INFO - hello world, this is the third task, it will run after first task and at the same time task 2
[2024-07-18 05:58:57,148] {bash.py:177} INFO - Command exited with return code 0
[2024-07-18 05:58:57,206] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v3, task_id=third_task, execution_date=20240718T055854, start_date=20240718T055856, end_date=20240718T055857
[2024-07-18 05:58:57,266] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-18 05:58:57,274] {local_task_job.py:146} INFO - Task exited with return code 0
